// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq44FBDhKdc73atGeECjGh2Jt6NOAZZpA',
    appId: '1:437753445814:web:f8560b533a7304d7cb5517',
    messagingSenderId: '437753445814',
    projectId: 'lab-assigment-39c63',
    authDomain: 'lab-assigment-39c63.firebaseapp.com',
    storageBucket: 'lab-assigment-39c63.firebasestorage.app',
    measurementId: 'G-N53RNRKGTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGy5uqNFui5lH4QkD_uwc1c2fQRk7UYXI',
    appId: '1:437753445814:android:f8ac26a8e876ce6fcb5517',
    messagingSenderId: '437753445814',
    projectId: 'lab-assigment-39c63',
    storageBucket: 'lab-assigment-39c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgB-BnLU2XtGzl1VkfWV6-F5vp7NaK8Y',
    appId: '1:437753445814:ios:eed7a979ef4daf93cb5517',
    messagingSenderId: '437753445814',
    projectId: 'lab-assigment-39c63',
    storageBucket: 'lab-assigment-39c63.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment1Chongshaoyi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgB-BnLU2XtGzl1VkfWV6-F5vp7NaK8Y',
    appId: '1:437753445814:ios:eed7a979ef4daf93cb5517',
    messagingSenderId: '437753445814',
    projectId: 'lab-assigment-39c63',
    storageBucket: 'lab-assigment-39c63.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment1Chongshaoyi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq44FBDhKdc73atGeECjGh2Jt6NOAZZpA',
    appId: '1:437753445814:web:32a455e4ab2776efcb5517',
    messagingSenderId: '437753445814',
    projectId: 'lab-assigment-39c63',
    authDomain: 'lab-assigment-39c63.firebaseapp.com',
    storageBucket: 'lab-assigment-39c63.firebasestorage.app',
    measurementId: 'G-43Z44NM6PS',
  );
}
